export const productos = [
    'Chorizo extra especial parrillero',
    'Chorizo extra expecial rueda',
    'Chorizo colorado rueda',
    'Chorizo colorado parrillero',
    'Chorizo relleno rueda',
    'Chorizo relleno parrillero',
    'Chorizo casero en rueda',
    'Chorizo casero parrillero',
    'Chorizo extra común parrillero',
    'Chorizo extra común rueda',
    'Chorizo puro de cerdo en rueda',
    'Chorizo puro de cerdo parrillero',
    'Chorizo seco',
    'Morcilla salada parrillera',
    'Morcilla dulce parrillera',
    'Morcilla vasca',
    'Chacarero x3',
    'Criollo x2',
    'Salamin x4',
    'Longaniza x2',
    'Picado fino 70',
    'Picado fino 90',
    'Picado fino aleman',
    'Picado fino aleman x2',
    'Milan',
    'Picado grueso 70',
    'Picado grueso 90',
    'Longaniza 90',
    'Longaniza Milan',
    'Longaniza picada fina',
    'Aleman especial',
    'Chacarero especial',
    'Longaniza especial',
    'Longaniza especial x2',
    'Aleman especial corto',
    'Chacarero especial corto',
    'Longaniza especial corta',
    'Longaniza esp. vacio',
    'Chacarero esp. vacio',
    'Aleman esp. vacio',
    'Caserito tradicional',
    'Caserito largo x2',
    'Caserito corto x2',
    'Caserito Pipa',
    'Sopressata x3',
    'Sopressata',
    'Jamón crudo',
    'Jamoncitos',
    'Capocuelo',
    'Capocuelo al vacío',
    'Bondiola cruda ahumada x2',
    'Bondiola cruda ahumada chica',
    'Bondiola cruda ahumada mediana',
    'Bondiola cruda ahumada grande',
    'Bondiola cruda ahumada vacio',
    'Panceta ahumada',
    'Panceta ahumada vacio',
    'Butifarra',
    'Grasa derretida cerdo',
    'Queso casero',
    'Queso casero vacio',
    'Mortadela x3',
    'Chorizo ruso',
    'Primavera',
    'Mortadela larga vacío',
    'Mortadela con morrón larga vacío',
    'Lionesa larga vacio',
    'Lionesa con jamón larga vacío',
    'Primavera larga vacio',
    'Chorizo Ruso largo vacio',
    'Carré ahumado',
    'Pamplona de cerdo',
    'Pamplona de vacuna',
    'Chicharrones de cerdo'
]