export const products = [
    { label: 'Chorizo extra especial parrillero', value: 'Chorizo extra especial parrillero' },
    { label: 'Chorizo extra expecial rueda', value: 'Chorizo extra expecial rueda' },
    { label: 'Chorizo colorado rueda', value: 'Chorizo colorado rueda' },
    { label: 'Chorizo colorado parrillero', value: 'Chorizo colorado parrillero' },
    { label: 'Chorizo relleno rueda', value: 'Chorizo relleno rueda' },
    { label: 'Chorizo relleno parrillero', value: 'Chorizo relleno parrillero' },
    { label: 'Chorizo casero en rueda', value: 'Chorizo casero en rueda' },
    { label: 'Chorizo casero parrillero', value: 'Chorizo casero parrillero' },
    { label: 'Chorizo extra común parrillero', value: 'Chorizo extra común parrillero' },
    { label: 'Chorizo extra común rueda', value: 'Chorizo extra común rueda' },
    { label: 'Chorizo puro de cerdo en rueda', value: 'Chorizo puro de cerdo en rueda' },
    { label: 'Chorizo puro de cerdo parrillero', value: 'Chorizo puro de cerdo parrillero' },
    { label: 'Chorizo seco', value: 'Chorizo seco' },
    { label: 'Morcilla salada parrillera', value: 'Morcilla salada parrillera' },
    { label: 'Morcilla dulce parrillera', value: 'Morcilla dulce parrillera' },
    { label: 'Morcilla vasca', value: 'Morcilla vasca' },
    { label: 'Chacarero x3', value: 'Chacarero x3' },
    { label: 'Criollo x2', value: 'Criollo x2' },
    { label: 'Salamin x4', value: 'Salamin x4' },
    { label: 'Longaniza x2', value: 'Longaniza x2' },
    { label: 'Picado fino 70', value: 'Picado fino 70' },
    { label: 'Picado fino 90', value: 'Picado fino 90' },
    { label: 'Picado fino aleman', value: 'Picado fino aleman' },,
    { label: 'Picado fino aleman x2', value: 'Picado fino aleman x2' },
    { label: 'Milan', value: 'Milan' },
    { label: 'Picado grueso 70', value: 'Picado grueso 70' },
    { label: 'Picado grueso 90', value: 'Picado grueso 90' },
    { label: 'Longaniza 90', value: 'Longaniza 90' },
    { label: 'Longaniza Milan', value: 'Longaniza Milan' },
    { label: 'Longaniza picada fina', value: 'Longaniza picada fina' },
    { label: 'Aleman especial', value: 'Aleman especial' },
    { label: 'Chacarero especial', value: 'Chacarero especial' },
    { label: 'Longaniza especial', value: 'Longaniza especial' },,
    { label: 'Longaniza especial x2', value: 'Longaniza especial x2' },
    { label: 'Aleman especial corto', value: 'Aleman especial corto' },
    { label: 'Chacarero especial corto', value: 'Chacarero especial corto' },,
    { label: 'Longaniza especial corta', value: 'Longaniza especial corta' },
    { label: 'Longaniza esp. vacio', value: 'Longaniza esp. vacio' },
    { label: 'Chacarero esp. vacio', value: 'Chacarero esp. vacio' },
    { label: 'Aleman esp. vacio', value: 'Aleman esp. vacio' },
    { label: 'Caserito tradicional', value: 'Caserito tradicional' },
    { label: 'Caserito largo x2', value: 'Caserito largo x2' },
    { label: 'Caserito corto x2', value: 'Caserito corto x2' },
    { label: 'Caserito Pipa', value: 'Caserito Pipa' },
    { label: 'Sopressata x3', value: 'Sopressata x3' },
    { label: 'Sopressata', value: 'Sopressata' },
    { label: 'Jamón crudo', value: 'amón crudo' },
    { label: 'Jamoncitos', value: 'Jamoncitos' },
    { label: 'Capocuelo', value: 'Capocuelo' },
    { label: 'Capocuelo al vacío', value: 'Capocuelo al vacío' },
    { label: 'Bondiola cruda ahumada x2', value: 'Bondiola cruda ahumada x2' },,
    { label: 'Bondiola cruda ahumada chica', value: 'Bondiola cruda ahumada chica' },
    { label: 'Bondiola cruda ahumada mediana', value: 'Bondiola cruda ahumada mediana' },
    { label: 'Bondiola cruda ahumada grande', value: 'Bondiola cruda ahumada grande' },
    { label: 'Bondiola cruda ahumada vacio', value: 'Bondiola cruda ahumada vacio' },
    { label: 'Panceta ahumada', value: 'Panceta ahumada' },
    { label: 'Panceta ahumada vacio', value: 'Panceta ahumada vacio' },
    { label: 'Butifarra', value: 'Butifarra' },
    { label: 'Grasa derretida cerdo', value: 'Grasa derretida cerdo' },,
    { label: 'Queso casero', value: 'Queso casero' },
    { label: 'Queso casero vacio', value: 'Queso casero vacio' },
    { label: 'Mortadela x3', value: 'Mortadela x3' },
    { label: 'Chorizo ruso', value: 'Chorizo ruso' },,
    { label: 'Primavera', value: 'Primavera' },
    { label: 'Mortadela larga vacío', value: 'Mortadela larga vacío' },
    { label: 'Mortadela con morrón larga vacío', value: 'Mortadela con morrón larga vacío' },
    { label: 'Lionesa larga vacio', value: 'Lionesa larga vacio' },
    { label: 'Lionesa con jamón larga vacío', value: 'Lionesa con jamón larga vacío' },
    { label: 'Primavera larga vacio', value: 'Primavera larga vacio' },
    { label: 'Chorizo Ruso largo vacio', value: 'Chorizo Ruso largo vacio' },
    { label: 'Carré ahumado', value: 'Carré ahumado' },
    { label: 'Pamplona de cerdo', value: 'Pamplona de cerdo' },
    { label: 'Pamplona de vacuna', value: 'Pamplona de vacuna' },
    { label: 'Chicharrones de cerdo', value: 'Chicharrones de cerdo' }
]